dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_d472159ded8f_key
  -iv $encrypted_d472159ded8f_iv -in .travis/keyrings/deploy_key.pem.enc -out .travis/keyrings/deploy_key.pem
  -d; fi
- export PATH=$PATH:${TRAVIS_BUILD_DIR}/target
- echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djava.security.egd=file:/dev/./urandom'"
  > ~/.mavenrc
install:
- sudo apt-get install gnupg2 -y
script:
- mvn --settings .travis/settings.xml clean test -B -U
after_success:
- mvn --settings .travis/settings.xml coveralls:report
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats
    branch: update-deploy
    jdk: oraclejdk8
env:
  global:
  - GPG_DIR=${TRAVIS_BUILD_DIR}/.travis/keyrings
  - secure: KgBpWDMGkR3vGfcdui+41jpsUglpV7c1H6Twlm7J2qxNfwJ5+gS9t2xE4OYFTbrwZfnlWQOv+lkfgrcFIblOsP7751rxE2t5kc2CQZXk6dIsryr5XvNs1z85Jxw3C2q/qdMtbUjn+F2XXqFfB7Cfq/euaoi2dM9/IaQHwaUQD+SJz4asrI56pQ/Gpa+qpgg3b/5wRMKGzo9K7n5pplqxw7NFaVHpepiAsVRR3UNIZ0cExQAXwuHAPKBYedkpc6avmlfH6U+DkX17pormNeWMx/vQKI3vqNhr+kf6MnZqNOMxQObzpTUUYcvRl47xJvT6eQVcIAujQJVJIIPKE46LVlk+ylYqsR+cfwQ1Gwk5dR7yHCnsNG+BpAGUErKvNdURqK3gL5BzNXgYG4+Xb4fYyE59fHi9OsgG7HNtlWovNMQJQA9FBQMFWONzsxEslx+8cFzm4T1Jm1Zwp5YgWr0Piw1OIr+lo2IDHyX0Vpqrjjapkn3tc5ZjI4ER/PYwuiFbhpHUBoyxHVIbMEOyNCTLtCiNeeb2pWGJztGiuiW8Rr5BP+URc6xW1I6oWAt0oFpIg6PkB6XlXm/z6Q/Fz3kzt+eNW/CXbB88sfqPVypaK420jL1A1jjZqKAbTe3D6QVumYvvQ8r/tj36eJNNQXX+ZmRAbq5+/kqKImyHVG7KUEE=
  - secure: sGMrCSRfokZkJaf/5QIEB9TgzyhKfFSmGHBJFn9oZ8j3oLYKPWke62fGtt86aZKxFDcAZ1x1hV4KbXsI/z2q/EnkCaTbs00wkQl9UGE+9C9T3Fnmuqoj6OD7YG/z6qwhh0KaRGQvc1UNtA+fwc3PEZjtnNBJ4j345wGKhqZcXh8+0BqSjZ7Uryia4d8cRdeJV+yM/q6YYBLibLS6GQTcuzblT0hhe0XG/oiXIGqrl5VV6eO2/7Wu3m5BXh/OXFmaiDoG2waJNbzwLvHVs7L4PKE9RkZIKRUdwWaUswME9sugVUmky1o8kuD/0vwMqbidT9SEodbFcEZQxUSalcfcrd6kPlMV8GSkHqk3V5RU9UPuAnHTVz778A7euk0yH4sC0hbiHLPzdoHqQdBxY6kJtYTRY1hOWPsfiITyE8Vy4mDkinnhGb+GtBJzGsXHIKVXpft5VM+cnstNLf3r+RSi3jrUg3zKTz9D5575yxQSQ35d6ttUR6NMgDtC77y14OLHFKSMkM90fFj5wIH7Rcx+v6Bk6ji5UsCLJkxpzUekWr6d9yhfXUoUpeX1lWcB8DsuEXU0lAbOG/NMAvFT1ZdhsAQ7P2RxzY6MKMZSw1IPYfjtrdXVTK4J++dW+iEp2jC9Liv/lFQAjAJ18Qw/NWQe70CE13KwCVesP4VjtUYlqIA=
  - secure: pueva7TFkZoscElCjZBL3aRxi8M6ieacFcT91UDRHvYqVo2AzMzH93P7Fme5VnapVnVWCTVlOhclvL+NU/0EayEByX/7TOOfo5I4/Q35WXodu1IrG96+Anuz3GP1h6YYt7fa7ezJ8h/KNHlsJTryRvhTemdHQF/HYZVNnmfDYybXJjDFaoPVesWcu7D9ofz45ACdMWVoi9DmRF8izUSIT8yMlNMA0qj65Yej0Fnu4+/dBklwO0ppSVfKQRkT4poBa4D5Pa8fdtiLv9QDXwU192IHbAPtotglGH7Q4b4YYS+VH/XSFZNmHF/PzKNEouNUtZlskSRbbAOlAtmbAJ6IMZZXqi/kTMSD8vIMNV7wTFksjBqRiJSjjFDd/qB5kwjrIB0HdjzFR67GWl1iQTLvlBt+1xvkEF71wD6BTku2jimHt4xsk9DyUYIeEpwJXuEK1O/AC/h764WILPDLIIxk+Q5oFrv3cPmzlGysGlbegeTDbNZaqaDA26sSqUQhgX6wjFFetXD2CBKMdXowzd03E+avYp+gvSuDHbgLkaz5RoN0+CyWDZrq4LxgQ1DZUQk+j2lXV8vQk7+/dLAsRUrUJwMm1LSiO8qgCffV8K9rPMFyBytovol+KSWfaNGKpknx7UESZzU5GnYw+NC/Fup9Ln/c4NG0okOz3g9vUIxhTaA=
  - secure: CBDgoCkfy/XeAYWi/kOC+7DsZ0LfDPjZXSEpJ3JOvH0O8WtHBws3kq9mVsP1jm0P3VZEoqXfk2LB5st7Md3CSeYMWNZQ3D2NNhoSyoK5JzEluunDNgaejnja2ZXQwbj0GYdR+QUXDIysEqZELST0rmWCfKDUeNc/jKORVLYya1kilbQ8Fe2bvrKYRig8yuyYu2DnBwu3dQGxfzogef1UyW3u734klMva+Ue2rgHtjP96Toa48Tz0s0qtIKZdeUDCBWuJ5OXPB/I+KR9VBxsfMCyrV99R2uNC4w8jYrIICX4JC5+49gjOPEE7U5LLCtX6mc3kMRkOEUVsSqtte0wyx5rveJ1K054ZqHZZ2Qkudu17ADvJq4XA0N+oq+BgAX6QyoskN7BwDEWP4u201yH6pQVUu8ApVfo2nVDb5LqacTmaxBBO1HUhUirPusFIjRmfguAG45kzvBgRlTTgwWephJvAAKm64dix8Mpt3006Jwh6lif/RTabkuT0BESBfRBiKOkKQqiEJgvOxZXGhiJvaqlo09fnjO6EeCMfq/3PmDfReRmWhMQNPzQvw4I/xiDIjOS6w055RCFwj98h+TIm+LtjC5VAn4hBaLIls6A1Sf6RDmXSb37yMivtRbwvy14dOdthU1n1iD/j8aLjmUHvuSYC7APdyGA8vJAuFW729QE=
  - secure: Wix4u8UWFGGXEkdT2n5V7OMWcnlKFIoalyROPzyxqZpBlon2uScH3NDYp2iQhM72OFK/0gvXZDw8OshnDyKve1Ay+qD7FpKGivWd2+reyvakEGI9gy5P+Z3A01EX1RMx0OKStKWUcTa/KptAgpYfjNPW4D5gKcc2TB9Ox8XZ3+/Y9YyQMB5vWuEAWy9JEETH6tY7WLaTaWQVitEZC29Lt0//UMwfWy5WrY/XDy5p/3BCOAoS2SbQwNGBHeMWvpKnw/v1uP5Vm+GXin+Q5lWifwMikYFo+EfmUqr/QuM9aWtrB1C7yMpsgwNdYiJ6TwHme4rFqkL7nv7OyOJw5dQ5D7ZhsNNLjPAug5+vpt73LekXNCN3611l8L3oa5ihp5+r8IqF7c65n2/+q7rrqSMHbB3mtuFG3nxY6QSFrk/eyIw13mSdK7YHIOnplQ6tbc4rxDOYeu95+zQ8/xZMvIpxt8eLXxTPNk07mPm99J1cx+CGng9YgSVjDwS7LAoZriejWdVCdggj7+vRhW5/A5TQ+24XMJzV7Y5b4PW1Xy3bHrz6k0qTh5Gg61bYLYleygaGaFstBSFZQBeGKIrgOHjxs65CmZxj23Y5kwwehZZ1ePtg0HWZcb8+P9f4K66dK+Bq2Ys6j65xq14ZmP99P4553lvROIfXAmGCvHvvwnTURjc=
