dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_d472159ded8f_key
  -iv $encrypted_d472159ded8f_iv -in .travis/keyrings/deploy_key.pem.enc -out .travis/keyrings/deploy_key.pem
  -d; fi
- export PATH=$PATH:${TRAVIS_BUILD_DIR}/target
- echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djava.security.egd=file:/dev/./urandom'"
  > ~/.mavenrc
install:
- sudo apt-get install -y gnupg2
script:
- mvn --settings .travis/settings.xml clean test -B -U
after_success:
- mvn --settings .travis/settings.xml coveralls:report
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats
    branch: update-deploy
    jdk: oraclejdk8
env:
  global:
  - GPG_DIR=${TRAVIS_BUILD_DIR}/.travis/keyrings
  - secure: joBt1t9VskVLhs+AgZgPyAxToSns4manJVVZxWp+/GSuXxUI++6d7Z6CrJff0XBcwpQIX/c/cP4aalH2w4gcJU8wP8UwEKHGakYdxxqYzpamyNglUUvmZzJPbFBZThW6xBgOQgV3PYpazRP/GBo+R1UypblKzOtHVMN1ijzQiyabrdjRJ1lkRzcksDFGVgejLzt26Pf4IJ9S+LaZCS66+AAUDKwmWl0XJ6iYyQ3tbI8t80VKge4NNc+q6bpalfNs3XcAI/1KbRG776d+GFhR2S2Ey1UjUYHVK/0uADu/nfQW1VS9busEdkCnCCRodKIRP501GK7IIUJ6JBlerKnl/Hk0/S//VDrHcNcV/1dhUN8mpS4LWdTVUfUDiM+Iy5npUjb2mDV1bSkUu/1K/oHzNT9UYJmmgCUHzqGERBEqZiM7UdLMafs5ZiCgdaVDVPfjdsfvGK94KKcJvKrkS2KsdIK/XcFZ4kwK5X4ukvpoNlK6Qf0bzkxBYEzuDY0EZ/Cp1Gfuz5F/f2x75/1hkjyMgsVs22ifY/lZe+4tdkXwvassAAP6gyLHXzBeN/DXfH54oQQKsw6BTi6pnQJgWf536fjQTyiBEAaP1qKrBIfnDURX28oKNRNoh0OefhVzwioHG555JVN4EOVn31J+yS64ZfbeIgUIPtueO66FUy0gMJc=
  - secure: ySQAapRa6mxFmNisQ9p+EWCwusDLQaa4x+gcWtHtvGoHxq+CB8y322NSYksENnTmwrUBBZLuY3qFuDU1hPeZTCoOmIBNItYeG6GeOPyqoPI0NZnmL8ecnbIwj65K+EAwYj+jqboubK/GRWekGsv4y/niN6ggJGT+bmAD0Nfo+TS7gEQt52q7g3x+cg5wrZLrOnrmU8QszLutAd7nn88noFksVtXQ0/379M2Ia476raBjBPkGGodaY2OUY5BUOPVqu0Wc22wbLN2dbMeMwMRxrS8iQk8pC12EM3gYGR1cKTdWksRYPkcj6sgA7YKmQqjkZEwdwE0ACLQCIJBsWGTVl3zlNoY9ubE0pI/gS7fkUnf1wmAsAYcq+9x+/oYqni8/D4VThZBuQPd6rWnd5BfTZwocb5oDL2R0uHOsmTycYTXB+QJYVKT3zrcnp7cvuFmOz9ol5EF2znp4zQn+K8juBGClBdXPa48GLRvVvMpNfpn9twve4AubYjJGtxet7dOiG3sMXvXFhO+SUVBZ+2qVXDfqttQAKZ3/lS2rNRMowmU1S5KEDuzTHdYr7krLaIck++5zHF4+EgWK64HQ9ajOu5b3GxmZtwnsh9hfOZ8Zbgx9Fcw/V5AtH2ZTEi7oUbGlc9NJqHQjYKDlux/oc9nVMk1+c9iY1zmvrDLG/cI5FEI=
  - secure: G86bGAIZIs/9qR2UyZRIOAAY5cuFkvp/2otqkP5mtVXWbPfv2oxLIHffIB6xnQhg8xllViCSO5wKKefxJmcj1fan5M2OrsjGQYMHyqOkDOjjuG4otmw89umm/RBgi/10vBwZ8NHFaH8E/CW8o5GBsCiFhrWUuph0G8Jp5GSdn5zHjo1cp/nThPemzQar5T3meRS5I7WcHvTZA8vzrsCHsfsWuceCUzY47IhFK0fRppgCm8eUQ3TG0z5Qu4AV2LLrHEsJ65I3yYn2W1QzP88hHTXTDR1Onxl2CqPfV2gqCSAaM2Frp5vpZq9rstKt19lXMIPonEwC3tu4eiCbk/+kHSVAFTJFKO+62U85lNZX3vEgKhybjiCyZoRZhNZpn0JOz3ymqmy+3L3TJyoQ49jNf/tto7kYds3LrXShnnmMHnB0sAbOCzv7aSRkt5Ph2wC4SIvJYxmbrl0HrvtZvfo7+e16jkSnUPk/KAwFAoxfCrx/6h5XjIHGrNr6D3ccud52D+C8fK8hvlOYuMcTi3zDNnuSZlIp9kzr5WjloQzADbaLlxuqsM0+5iL9A/y5q/CicsnmVQta/B6ytlOInn5md6dCQOQnG97TM4XSnLRdmYy+ROtMv7ptCh4OCaWmbRM5bxIZpVHl1d8hUHMuE0kM+rBwzuO8u07KLAOWVCxisKc=
  - secure: vUAf1ZoyylmUk+6K7hp77VfkXkL3F/6pN5SO3wadOipORu1C0ODU+mHkfXZtPaSOk6KwiKUX496ycD/91XspYNfBIjGHPvFroWmgEOWpFGPv6HlPZjCpt+YVhkdbMGuRqR/rcQBdruDxdlgFHvPkUQF3gGqju5Ohrw8LVjJpQ4ygUK7bcaER0qpo3dpXtNXaqRpzdyQJ6j8nzs6LJSg3b3gbAlNAOrnTC8la78ywVRbuagGVv93gwMHZWoueOvueWBoySjj/G2jcArJEWfsEUHk0LeISikxdpfLPtuZP9xzqV0ky8CKP+XXj0ZM+SMnahv0+Wb6BwHNpm1e7/JsuKo8lUjmjfh0fg96CZX0Z4gimATVWrJhxOmUbFZ5BKEP91Z9YTipw2zTiuZdlbIOQ4zxX2RYOPQhF8xNR30Iyekzc9O1fCq0zxD88+10mtRajaM7WhPeYwLGVpZXOWn0JyBtEi8AByDI+tQrAJ3M7L2CDydviuQ/n3kC1WVWlRmrNAZRn2c+DwosWJQgpGJcZ7Mc0MeSZXi0PHYWsGFMTd9wXdPpH4Fu0+aJYnQtOxMDmWKNLbs3olBt/oH2sSOzx2f7Ow624eAS3vgwGna0zLAN+KFA8a+hVBKfJ+KQuYVanBWpyUVuitOI8W3oRJw9BSe3ec3F9b2BDQHvpHYj1Pto=
  - secure: yRyHsyavTF7M3Clpy8WVEbtdKMIwnZq9MvN7RoJAhYGrmrBg0sQcjC2HqPAPZqibldUoNOiCYHjOENDy2IZFghL+trH7C9kgQgEAFVfZk6LLR3q+h+gq9NSsTrgLC081deNLGE0hvs3sCN1IW9sfozWXCNZoRc1JLZbDOfNPrh4P781cDs6dTIiC5a/lAJOmW/FXZMzdxTi3/yc7Md2v7kH3/9x8WI6Aj7cHeOtc6ROOgVXwmtzo56br9eCFqU+qgt1RsIrd+EpocsgqOTZsoNROpf9nox2wU6vVE/bLz+88tHgOEZo/2/CU1vZi5avDjMSbmipGUPJiFeyEfe/J4enGUUJBtqxNJuMPm6ZwtaaOLeHwpSCQkbckCFo2DU5b/mVkF7D9iu2CCRy2PinsTTXO9Zujic2XIQWf5+xOqetWE2W3xc4V3xgGHn+wdJUujutC3JYiW7YslVJclGNKhVwCXN1TjgFcy+CkLvywoqIKK4qoPX3hqNrnAdXok2JlvxaimSE0/Tsm+/4xFFzaY79eGlauoaDd6imRJUC5kUVjQgO0m5Qz5bMI0amUzsUC43Qo9iFMeiom4Un49WRVGLvAVgG/WovbDJwv7Edg5zJyCmZVjSt6hcJarP/sjbOY8EWd/MczSjrRI1VumjUHtA02x6Hq/PmEk92AyTUpSh0=
